<?php

namespace App\Controllers;

use App\Models\UserModel;
use App\Models\UserRoleModel;
use App\Models\OpdModel;
use App\Models\BidangModel;

class UserController extends BaseController
{
    protected $userModel;
    protected $userRoleModel;
    protected $opdModel;
    protected $bidangModel;

    public function __construct()
    {
        $this->userModel = new UserModel();
        $this->userRoleModel = new UserRoleModel();
        $this->opdModel = new OpdModel();
        $this->bidangModel = new BidangModel();
        helper('logger');
    }

    public function index()
    {
        $role = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        // Fetch users based on role
        $builder = $this->userModel->db->table('users')
            ->select('users.*, roles.nama_role, opd.nama_opd, bidang.nama_bidang')
            ->join('user_roles', 'user_roles.id_user = users.id_user', 'left')
            ->join('roles', 'roles.id_role = user_roles.id_role', 'left')
            ->join('opd', 'opd.id_opd = users.id_opd', 'left')
            ->join('bidang', 'bidang.id_bidang = users.id_bidang', 'left');

        if ($role === 'Admin_Pemkab') {
            // Admin Pemkab hanya mengelola Admin OPD
            $builder->where('roles.nama_role', 'Admin_OPD');
        } elseif ($role === 'Admin_OPD') {
            // Admin OPD mengelola user di OPD yang sama, kecuali Admin_Pemkab dan Admin_OPD
            $builder->where('users.id_opd', $idOpd);
            $builder->whereNotIn('roles.nama_role', ['Admin_Pemkab', 'Admin_OPD']);
        } else {
            return redirect()->to('/dashboard')->with('error', 'Akses Ditolak.');
        }

        $data['users'] = $builder->orderBy('users.created_at', 'DESC')->get()->getResultArray();
        return view('user/index', $data);
    }

    public function create()
    {
        $role = session()->get('nama_role');
        $data['opds'] = $this->opdModel->findAll();
        
        // Ambil data role yang unik untuk dropdown
        $rolesBuilder = $this->userModel->db->table('roles')->select('MAX(id_role) as id_role, nama_role')->groupBy('nama_role');
        if ($role === 'Admin_Pemkab') {
            $rolesBuilder->where('nama_role', 'Admin_OPD');
        } elseif ($role === 'Admin_OPD') {
            $rolesBuilder->whereNotIn('nama_role', ['Admin_Pemkab', 'Admin_OPD']);
            $data['bidangs'] = $this->bidangModel->where('id_opd', session()->get('id_opd'))->findAll();
        }
        $data['roles'] = $rolesBuilder->get()->getResultArray();
        $data['userRole'] = $role;

        return view('user/create', $data);
    }

    public function store()
    {
        $roleLogin = session()->get('nama_role');
        
        // Validasi input
        $rules = [
            'nama' => 'required|max_length[100]',
            'email' => 'required|valid_email|is_unique[users.email]',
            'id_role' => 'required'
        ];

        if ($roleLogin === 'Admin_Pemkab') {
            $rules['id_opd'] = 'required';
        }

        if (! $this->validate($rules)) {
            return redirect()->back()->withInput()->with('error', 'Silakan periksa kembali data Anda: ' . implode(', ', $this->validator->getErrors()));
        }

        $idOpd = $roleLogin === 'Admin_OPD' ? session()->get('id_opd') : $this->request->getPost('id_opd');
        
        $userData = [
            'nama' => $this->request->getPost('nama'),
            'email' => $this->request->getPost('email'),
            'password' => password_hash('Admin123!', PASSWORD_DEFAULT),
            'id_opd' => $idOpd,
            'id_bidang' => $this->request->getPost('id_bidang') ?: null,
            'is_active' => 1,
            'is_default_password' => 1
        ];

        $this->userModel->db->transStart();
        
        $this->userModel->insert($userData);
        $userId = $this->userModel->getInsertID(); // getInsertID returns the UUID generated by BaseModel

        $userRoleData = [
            'id_user' => $userId,
            'id_role' => $this->request->getPost('id_role')
        ];
        $this->userRoleModel->insert($userRoleData);

        $this->userModel->db->transComplete();

        if ($this->userModel->db->transStatus() === false) {
            return redirect()->back()->withInput()->with('error', 'Gagal membuat akun.');
        }

        log_activity('Users', 'CREATE', 'Membuat akun pengguna baru: ' . $userData['nama']);
        return redirect()->to('/users')->with('success', 'Akun berhasil dibuat dengan password default: Admin123!');
    }

    public function edit($id)
    {
        $role = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        // Validasi akses
        $user = $this->userModel->find($id);
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        // Ambil role pengguna yang diedit
        $editedUserRole = $this->userRoleModel->where('id_user', $id)->first();
        $roleInfo = $this->userModel->db->table('roles')->where('id_role', $editedUserRole['id_role'])->get()->getRowArray();

        if ($role === 'Admin_Pemkab') {
            if ($roleInfo['nama_role'] !== 'Admin_OPD') {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        } elseif ($role === 'Admin_OPD') {
            if ($user['id_opd'] !== $idOpd || in_array($roleInfo['nama_role'], ['Admin_Pemkab', 'Admin_OPD'])) {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        }

        $data['user'] = $user;
        $data['current_role'] = $editedUserRole['id_role'];
        $data['opds'] = $this->opdModel->findAll();
        
        $rolesBuilder = $this->userModel->db->table('roles')->select('MAX(id_role) as id_role, nama_role')->groupBy('nama_role');
        if ($role === 'Admin_Pemkab') {
            $rolesBuilder->where('nama_role', 'Admin_OPD');
        } elseif ($role === 'Admin_OPD') {
            $rolesBuilder->whereNotIn('nama_role', ['Admin_Pemkab', 'Admin_OPD']);
            $data['bidangs'] = $this->bidangModel->where('id_opd', session()->get('id_opd'))->findAll();
        }
        $data['roles'] = $rolesBuilder->get()->getResultArray();
        $data['userRole'] = $role;

        return view('user/edit', $data);
    }

    public function update($id)
    {
        $roleLogin = session()->get('nama_role');
        $user = $this->userModel->find($id);
        
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        $rules = [
            'nama' => 'required|max_length[100]',
            'id_role' => 'required',
            'email' => 'required|valid_email|is_unique[users.email,id_user,'.$id.']',
        ];

        if ($roleLogin === 'Admin_Pemkab') {
            $rules['id_opd'] = 'required';
        }

        if (! $this->validate($rules)) {
            return redirect()->back()->withInput()->with('error', 'Silakan periksa kembali data Anda: ' . implode(', ', $this->validator->getErrors()));
        }

        $idOpd = $roleLogin === 'Admin_OPD' ? session()->get('id_opd') : $this->request->getPost('id_opd');

        $userData = [
            'nama' => $this->request->getPost('nama'),
            'email' => $this->request->getPost('email'),
            'id_opd' => $idOpd,
            'id_bidang' => $this->request->getPost('id_bidang') ?: null,
            'is_active' => $this->request->getPost('is_active') ? 1 : 0
        ];

        $this->userModel->db->transStart();
        
        $updUser = $this->userModel->update($id, $userData);
        if (!$updUser) {
            $this->userModel->db->transRollback();
            return redirect()->back()->withInput()->with('error', 'Gagal update data user: ' . implode(', ', $this->userModel->errors()));
        }
        
        // Update role
        $updRole = $this->userRoleModel->update($id, ['id_role' => $this->request->getPost('id_role')]);
        if ($updRole === false) {
            $this->userModel->db->transRollback();
            $dbError = $this->userRoleModel->db->error();
            $modelErrors = $this->userRoleModel->errors();
            $errorMsg = !empty($modelErrors) ? implode(', ', $modelErrors) : ($dbError['message'] ?? 'Unknown error');
            return redirect()->back()->withInput()->with('error', 'Gagal update role user: ' . $errorMsg);
        }

        $this->userModel->db->transComplete();

        if ($this->userModel->db->transStatus() === false) {
            $error = $this->userModel->db->error();
            return redirect()->back()->withInput()->with('error', 'Gagal memperbarui akun: ' . ($error['message'] ?? 'Unknown DB error'));
        }

        log_activity('Users', 'UPDATE', 'Memperbarui data pengguna: ' . $userData['nama'], $user, $userData);
        return redirect()->to('/users')->with('success', 'Akun berhasil diperbarui.');
    }

    public function delete($id)
    {
        $roleLogin = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        $user = $this->userModel->find($id);
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        $editedUserRole = $this->userRoleModel->where('id_user', $id)->first();
        $roleInfo = $this->userModel->db->table('roles')->where('id_role', $editedUserRole['id_role'])->get()->getRowArray();

        if ($roleLogin === 'Admin_Pemkab') {
            if ($roleInfo['nama_role'] !== 'Admin_OPD') {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        } elseif ($roleLogin === 'Admin_OPD') {
            if ($user['id_opd'] !== $idOpd || in_array($roleInfo['nama_role'], ['Admin_Pemkab', 'Admin_OPD'])) {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        }

        $this->userModel->db->transStart();
        $this->userRoleModel->where('id_user', $id)->delete();
        $this->userModel->delete($id);
        $this->userModel->db->transComplete();

        if ($this->userModel->db->transStatus() === false) {
            return redirect()->to('/users')->with('error', 'Gagal menghapus akun.');
        }

        log_activity('Users', 'DELETE', 'Menghapus akun pengguna: ' . $user['nama']);
        return redirect()->to('/users')->with('success', 'Akun berhasil dihapus.');
    }

    public function resetPassword($id)
    {
        $roleLogin = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        $user = $this->userModel->find($id);
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        $editedUserRole = $this->userRoleModel->where('id_user', $id)->first();
        $roleInfo = $this->userModel->db->table('roles')->where('id_role', $editedUserRole['id_role'])->get()->getRowArray();

        // Validasi akses seperti edit
        if ($roleLogin === 'Admin_Pemkab') {
            if ($roleInfo['nama_role'] !== 'Admin_OPD') {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        } elseif ($roleLogin === 'Admin_OPD') {
            if ($user['id_opd'] !== $idOpd || in_array($roleInfo['nama_role'], ['Admin_Pemkab', 'Admin_OPD'])) {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        }

        $this->userModel->update($id, [
            'password' => password_hash('Admin123!', PASSWORD_DEFAULT),
            'is_default_password' => 1
        ]);

        log_activity('Users', 'UPDATE', 'Mereset password pengguna ke default: ' . $user['nama']);
        return redirect()->back()->with('success', 'Password berhasil di-reset ke default (Admin123!). Pengguna akan diminta untuk mengganti password saat login.');
    }
}
