<?php

namespace App\Controllers;

use App\Models\UserModel;
use App\Models\UserRoleModel;
use App\Models\OpdModel;
use App\Models\BidangModel;

class UserController extends BaseController
{
    protected $userModel;
    protected $userRoleModel;
    protected $opdModel;
    protected $bidangModel;

    public function __construct()
    {
        $this->userModel = new UserModel();
        $this->userRoleModel = new UserRoleModel();
        $this->opdModel = new OpdModel();
        $this->bidangModel = new BidangModel();
        helper('logger');
    }

    public function index()
    {
        $role = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        // Fetch users based on role
        $builder = $this->userModel->db->table('users')
            ->select('users.*, roles.nama_role, opd.nama_opd, bidang.nama_bidang')
            ->join('user_roles', 'user_roles.id_user = users.id_user', 'left')
            ->join('roles', 'roles.id_role = user_roles.id_role', 'left')
            ->join('opd', 'opd.id_opd = users.id_opd', 'left')
            ->join('bidang', 'bidang.id_bidang = users.id_bidang', 'left');

        if ($role === 'Admin_Pemkab') {
            // Admin Pemkab hanya mengelola Admin OPD
            $builder->where('roles.nama_role', 'Admin_OPD');
        } elseif ($role === 'Admin_OPD') {
            // Admin OPD mengelola user di OPD yang sama, kecuali Admin_Pemkab dan Admin_OPD
            $builder->where('users.id_opd', $idOpd);
            $builder->whereNotIn('roles.nama_role', ['Admin_Pemkab', 'Admin_OPD']);
        } else {
            return redirect()->to('/dashboard')->with('error', 'Akses Ditolak.');
        }

        $data['users'] = $builder->orderBy('users.created_at', 'DESC')->get()->getResultArray();
        return view('user/index', $data);
    }

    public function create()
    {
        $role = session()->get('nama_role');
        $data['opds'] = $this->opdModel->findAll();
        
        // Ambil data role yang unik untuk dropdown
        $rolesBuilder = $this->userModel->db->table('roles')->select('MAX(id_role) as id_role, nama_role')->groupBy('nama_role');
        if ($role === 'Admin_Pemkab') {
            $rolesBuilder->where('nama_role', 'Admin_OPD');
        } elseif ($role === 'Admin_OPD') {
            $rolesBuilder->whereNotIn('nama_role', ['Admin_Pemkab', 'Admin_OPD']);
            $data['bidangs'] = $this->bidangModel->where('id_opd', session()->get('id_opd'))->findAll();
        }
        $data['roles'] = $rolesBuilder->get()->getResultArray();
        $data['userRole'] = $role;

        return view('user/create', $data);
    }

    public function store()
    {
        $roleLogin = session()->get('nama_role');
        
        // Validasi input
        $rules = [
            'nama' => 'required|max_length[100]',
            'email' => 'required|valid_email|is_unique[users.email]',
            'id_role' => 'required'
        ];

        if ($roleLogin === 'Admin_Pemkab') {
            $rules['id_opd'] = 'required';
        }

        if (! $this->validate($rules)) {
            return redirect()->back()->withInput()->with('error', 'Silakan periksa kembali data Anda: ' . implode(', ', $this->validator->getErrors()));
        }

        $idOpd = $roleLogin === 'Admin_OPD' ? session()->get('id_opd') : $this->request->getPost('id_opd');
        
        $userData = [
            'nama' => $this->request->getPost('nama'),
            'email' => $this->request->getPost('email'),
            'password' => password_hash('Admin123!', PASSWORD_DEFAULT),
            'id_opd' => $idOpd,
            'id_bidang' => $this->request->getPost('id_bidang') ?: null,
            'is_active' => 1,
            'is_default_password' => 1
        ];

        $this->userModel->db->transStart();
        
        $this->userModel->insert($userData);
        $userId = $this->userModel->getInsertID(); // getInsertID returns the UUID generated by BaseModel

        $userRoleData = [
            'id_user' => $userId,
            'id_role' => $this->request->getPost('id_role')
        ];
        $this->userRoleModel->insert($userRoleData);

        $this->userModel->db->transComplete();

        if ($this->userModel->db->transStatus() === false) {
            return redirect()->back()->withInput()->with('error', 'Gagal membuat akun.');
        }

        log_activity('Users', 'CREATE', 'Membuat akun pengguna baru: ' . $userData['nama']);
        return redirect()->to('/users')->with('success', 'Akun berhasil dibuat dengan password default: Admin123!');
    }

    public function edit($id)
    {
        $role = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        // Validasi akses
        $user = $this->userModel->find($id);
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        // Ambil role pengguna yang diedit
        $editedUserRole = $this->userRoleModel->where('id_user', $id)->first();
        $roleInfo = $this->userModel->db->table('roles')->where('id_role', $editedUserRole['id_role'])->get()->getRowArray();

        if ($role === 'Admin_Pemkab') {
            if ($roleInfo['nama_role'] !== 'Admin_OPD') {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        } elseif ($role === 'Admin_OPD') {
            if ($user['id_opd'] !== $idOpd || in_array($roleInfo['nama_role'], ['Admin_Pemkab', 'Admin_OPD'])) {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        }

        $data['user'] = $user;
        $data['current_role'] = $editedUserRole['id_role'];
        $data['opds'] = $this->opdModel->findAll();
        
        $rolesBuilder = $this->userModel->db->table('roles')->select('MAX(id_role) as id_role, nama_role')->groupBy('nama_role');
        if ($role === 'Admin_Pemkab') {
            $rolesBuilder->where('nama_role', 'Admin_OPD');
        } elseif ($role === 'Admin_OPD') {
            $rolesBuilder->whereNotIn('nama_role', ['Admin_Pemkab', 'Admin_OPD']);
            $data['bidangs'] = $this->bidangModel->where('id_opd', session()->get('id_opd'))->findAll();
        }
        $data['roles'] = $rolesBuilder->get()->getResultArray();
        $data['userRole'] = $role;

        return view('user/edit', $data);
    }

    public function update($id)
    {
        $roleLogin = session()->get('nama_role');
        $user = $this->userModel->find($id);
        
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        $rules = [
            'nama' => 'required|max_length[100]',
            'id_role' => 'required',
            'email' => 'required|valid_email|is_unique[users.email,id_user,'.$id.']',
        ];

        if ($roleLogin === 'Admin_Pemkab') {
            $rules['id_opd'] = 'required';
        }

        if (! $this->validate($rules)) {
            return redirect()->back()->withInput()->with('error', 'Silakan periksa kembali data Anda: ' . implode(', ', $this->validator->getErrors()));
        }

        $idOpd = $roleLogin === 'Admin_OPD' ? session()->get('id_opd') : $this->request->getPost('id_opd');

        $userData = [
            'nama' => $this->request->getPost('nama'),
            'email' => $this->request->getPost('email'),
            'id_opd' => $idOpd,
            'id_bidang' => $this->request->getPost('id_bidang') ?: null,
            'is_active' => $this->request->getPost('is_active') ? 1 : 0
        ];

        $this->userModel->db->transStart();
        
        $updUser = $this->userModel->update($id, $userData);
        if (!$updUser) {
            $this->userModel->db->transRollback();
            return redirect()->back()->withInput()->with('error', 'Gagal update data user: ' . implode(', ', $this->userModel->errors()));
        }
        
        // Update role
        $updRole = $this->userRoleModel->update($id, ['id_role' => $this->request->getPost('id_role')]);
        if ($updRole === false) {
            $this->userModel->db->transRollback();
            $dbError = $this->userRoleModel->db->error();
            $modelErrors = $this->userRoleModel->errors();
            $errorMsg = !empty($modelErrors) ? implode(', ', $modelErrors) : ($dbError['message'] ?? 'Unknown error');
            return redirect()->back()->withInput()->with('error', 'Gagal update role user: ' . $errorMsg);
        }

        $this->userModel->db->transComplete();

        if ($this->userModel->db->transStatus() === false) {
            $error = $this->userModel->db->error();
            return redirect()->back()->withInput()->with('error', 'Gagal memperbarui akun: ' . ($error['message'] ?? 'Unknown DB error'));
        }

        log_activity('Users', 'UPDATE', 'Memperbarui data pengguna: ' . $userData['nama'], $user, $userData);
        return redirect()->to('/users')->with('success', 'Akun berhasil diperbarui.');
    }

    public function delete($id)
    {
        $roleLogin = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        $user = $this->userModel->find($id);
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        $editedUserRole = $this->userRoleModel->where('id_user', $id)->first();
        $roleInfo = $this->userModel->db->table('roles')->where('id_role', $editedUserRole['id_role'])->get()->getRowArray();

        if ($roleLogin === 'Admin_Pemkab') {
            if ($roleInfo['nama_role'] !== 'Admin_OPD') {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        } elseif ($roleLogin === 'Admin_OPD') {
            if ($user['id_opd'] !== $idOpd || in_array($roleInfo['nama_role'], ['Admin_Pemkab', 'Admin_OPD'])) {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        }

        $this->userModel->db->transStart();
        $this->userRoleModel->where('id_user', $id)->delete();
        $this->userModel->delete($id);
        $this->userModel->db->transComplete();

        if ($this->userModel->db->transStatus() === false) {
            return redirect()->to('/users')->with('error', 'Gagal menghapus akun.');
        }

        log_activity('Users', 'DELETE', 'Menghapus akun pengguna: ' . $user['nama']);
        return redirect()->to('/users')->with('success', 'Akun berhasil dihapus.');
    }

    public function resetPassword($id)
    {
        $roleLogin = session()->get('nama_role');
        $idOpd = session()->get('id_opd');

        $user = $this->userModel->find($id);
        if (!$user) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        $editedUserRole = $this->userRoleModel->where('id_user', $id)->first();
        $roleInfo = $this->userModel->db->table('roles')->where('id_role', $editedUserRole['id_role'])->get()->getRowArray();

        // Validasi akses seperti edit
        if ($roleLogin === 'Admin_Pemkab') {
            if ($roleInfo['nama_role'] !== 'Admin_OPD') {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        } elseif ($roleLogin === 'Admin_OPD') {
            if ($user['id_opd'] !== $idOpd || in_array($roleInfo['nama_role'], ['Admin_Pemkab', 'Admin_OPD'])) {
                return redirect()->to('/users')->with('error', 'Akses Ditolak.');
            }
        }

        $this->userModel->update($id, [
            'password' => password_hash('Admin123!', PASSWORD_DEFAULT),
            'is_default_password' => 1
        ]);

        log_activity('Users', 'UPDATE', 'Mereset password pengguna ke default: ' . $user['nama']);
        return redirect()->back()->with('success', 'Password berhasil di-reset ke default (Admin123!). Pengguna akan diminta untuk mengganti password saat login.');
    }

    // =========================================================================
    // Switch Role / User Impersonation (Khusus Admin Pemkab)
    // =========================================================================

    /**
     * Admin Pemkab "menyamar" sebagai user lain untuk inspeksi.
     * Menyimpan data session asli Admin ke `original_admin_*`.
     */
    public function switchUser($userId)
    {
        $session = session();

        // Hanya Admin_Pemkab asli yang bisa switch (cek role asli atau role saat ini)
        $currentRole = $session->get('nama_role');
        $isAlreadySwitched = $session->has('original_admin_id');

        if ($currentRole !== 'Admin_Pemkab' && !$isAlreadySwitched) {
            return redirect()->to('/dashboard')->with('error', 'Akses Ditolak. Hanya Admin Pemkab yang bisa menggunakan fitur ini.');
        }

        // Cari user target
        $targetUser = $this->userModel->find($userId);
        if (!$targetUser) {
            return redirect()->to('/users')->with('error', 'Pengguna tidak ditemukan.');
        }

        // Ambil role target
        $targetUserRole = $this->userRoleModel->where('id_user', $userId)->first();
        if (!$targetUserRole) {
            return redirect()->to('/users')->with('error', 'Role pengguna tidak ditemukan.');
        }
        $roleInfo = $this->userModel->db->table('roles')->where('id_role', $targetUserRole['id_role'])->get()->getRowArray();

        // Jangan izinkan switch ke sesama Admin Pemkab
        if ($roleInfo['nama_role'] === 'Admin_Pemkab') {
            return redirect()->to('/users')->with('error', 'Tidak dapat menyamar sebagai Admin Pemkab lain.');
        }

        // Simpan data admin asli (hanya jika belum pernah switch sebelumnya)
        if (!$isAlreadySwitched) {
            $session->set([
                'original_admin_id'    => $session->get('user_id'),
                'original_admin_email' => $session->get('email'),
                'original_admin_nama'  => $session->get('nama_lengkap'),
                'original_admin_role'  => $session->get('nama_role'),
                'original_admin_id_role' => $session->get('id_role'),
                'original_admin_id_opd'  => $session->get('id_opd'),
                'original_admin_id_bidang' => $session->get('id_bidang'),
            ]);
        }

        // Ambil nama OPD untuk banner
        $namaOpd = '-';
        if ($targetUser['id_opd']) {
            $opd = $this->opdModel->find($targetUser['id_opd']);
            $namaOpd = $opd ? $opd['nama_opd'] : '-';
        }

        // Switch session ke user target
        $session->set([
            'user_id'             => $targetUser['id_user'],
            'email'               => $targetUser['email'],
            'nama_lengkap'        => $targetUser['nama'],
            'id_role'             => $targetUserRole['id_role'],
            'nama_role'           => $roleInfo['nama_role'],
            'id_opd'              => $targetUser['id_opd'],
            'id_bidang'           => $targetUser['id_bidang'],
            'is_default_password' => 0, // Admin tidak perlu ganti password saat impersonation
            'impersonated_opd_nama' => $namaOpd,
        ]);

        log_activity('Users', 'SWITCH_ROLE', 'Admin Pemkab menyamar sebagai: ' . $targetUser['nama'] . ' (' . $roleInfo['nama_role'] . ')');

        return redirect()->to('/dashboard')->with('success', 'Anda sekarang menyamar sebagai: ' . $targetUser['nama'] . ' (' . $roleInfo['nama_role'] . ')');
    }

    /**
     * Mengembalikan session Admin Pemkab ke akun aslinya.
     */
    public function switchBack()
    {
        $session = session();

        if (!$session->has('original_admin_id')) {
            return redirect()->to('/dashboard')->with('error', 'Anda tidak sedang dalam mode penyamaran.');
        }

        // Kembalikan session ke data admin asli
        $session->set([
            'user_id'             => $session->get('original_admin_id'),
            'email'               => $session->get('original_admin_email'),
            'nama_lengkap'        => $session->get('original_admin_nama'),
            'nama_role'           => $session->get('original_admin_role'),
            'id_role'             => $session->get('original_admin_id_role'),
            'id_opd'              => $session->get('original_admin_id_opd'),
            'id_bidang'           => $session->get('original_admin_id_bidang'),
            'is_default_password' => 0,
        ]);

        // Hapus data impersonation dari session
        $session->remove([
            'original_admin_id', 'original_admin_email', 'original_admin_nama',
            'original_admin_role', 'original_admin_id_role',
            'original_admin_id_opd', 'original_admin_id_bidang',
            'impersonated_opd_nama',
        ]);

        log_activity('Users', 'SWITCH_BACK', 'Admin Pemkab kembali ke akun asli.');

        return redirect()->to('/dashboard')->with('success', 'Anda telah kembali ke akun Admin Pemkab.');
    }
}
